name: 'Tests: node.js >= 20'

on: [pull_request, push]

jobs:
  tests:
    uses: ljharb/actions/.github/workflows/node.yml@main
    with:
      range: '^20.19 || ^22.19 || >= 24.7'
      type: minors
      command: npm run tests-only

  node:
    name: 'node >= 20'
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - run: true
